name: match_prot_to_genbank_nt
channels:
  - conda-forge
  - bioconda

dependencies:
  - biopython=1.85
  - blast=2.16
  - jupyterlab
  - ncbi-datasets-cli=18.0
  - pandas=2.2
  - python=3.12
  - seqkit=2.10
